apiVersion: v1  # 不要改动
kind: Plugin  # 不要改动
metadata:
  # author 和 name 唯一确定一个插件
  author: BUGJI  # 插件作者，修改为你的名称
  name: LangBot_CCB  # 插件名称，修改为你的插件名称
  repository: 'CCB'  # 插件仓库地址，修改为你的插件 GitHub 仓库地址
  version: 0.1.0  # 插件版本，修改为你的插件版本
  description:  # 插件简介，修改为你的插件简介，支持多语言
    en_US: 触发AI后输入XXX笑传之XXX即可进行自动CCB评级（代码内有接入AI的版本）
    zh_CN: 触发AI后输入XXX笑传之XXX即可进行自动CCB评级（代码内有接入AI的版本）
  label:  # 插件显示名称，支持多语言。在 WebUI 上会显示对应语言的 label
    en_US: CCB
    zh_CN: CCB
execution:
  python:
    path: main.py  # 插件主程序路径，必须与上方插件入口代码的文件名相同
    attr: CCB  # 插件类名，必须与上方代码中声明的类名相同
